# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-25 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180425_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='bot_question_id',
            new_name='bot_question',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_message_id',
            new_name='user_message',
        ),
    ]
